CREATE TABLE BorgerUser
(
    Id        INTEGER PRIMARY KEY AUTOINCREMENT,
    UserId    INTEGER NOT NULL,
    CreatedAt DATE DEFAULT CURRENT_TIMESTAMP
);

DROP TABLE IF EXISTS Address;

CREATE TABLE Address
(
    Id           INTEGER PRIMARY KEY AUTOINCREMENT,
    BorgerUserId INTEGER NOT NULL,
    Address      TEXT NOT NULL, 
    CreatedAt    DATE             DEFAULT CURRENT_TIMESTAMP,
    IsValid      INTEGER NOT NULL DEFAULT TRUE,
    FOREIGN KEY (BorgerUserId) REFERENCES BorgerUser (Id) ON DELETE CASCADE
);